insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Tenderloin Tails', 6333);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Orange, 341 Ml', 8508);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Sushi Flat Iron Steak', 3832);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Brick With Pepper', 5211);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Food Colouring - Pink', 7913);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Cooking Spray', 3438);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Basil - Primerba, Paste', 8865);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Syrup - Monin, Swiss Choclate', 3071);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - Strong', 8344);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Kale - Red', 9847);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bacon Strip Precooked', 6218);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Rosee', 9327);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Compound - Strawberry', 8920);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lamb - Racks, Frenched', 8552);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Tenderloin Tails', 4754);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cumin - Ground', 9349);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Petite Baguette', 5426);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mahi Mahi', 441);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce Tomato Pouch', 3673);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Water, Tap', 8751);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Parsley - Fresh', 301);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Truffle Paste', 3983);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Placido Pinot Grigo', 789);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mop Head - Cotton, 24 Oz', 2431);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Liqueur - Melon', 2165);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes - Cherry', 7847);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Gherkin - Sour', 4340);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Bacon, Sliced', 5848);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ecolab - Hand Soap Form Antibac', 9458);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Egg - Salad Premix', 1225);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Broccoli', 7470);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dr. Pepper - 355ml', 3073);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Water - Perrier', 2890);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 53x53 White', 8056);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ezy Change Mophandle', 7493);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Carrot - Individual', 5839);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pears - Bosc', 6571);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dip - Tapenade', 2260);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Sweetbread', 3722);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Sour Sticks With Onion', 3184);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Marinara', 2345);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Port - 74 Brights', 2327);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Shortbread - Cookie Crumbs', 7295);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - White, Mix', 4148);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mousse - Banana Chocolate', 8714);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Saint Emilion Calvet', 3134);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Steamers White', 3601);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sea Bass - Whole', 3411);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Hummus - Spread', 1524);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Goat - Whole Cut', 9558);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Rubyport', 983);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Jaboulet Cotes Du Rhone', 95);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Turnip - Wax', 3115);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Sunflower', 3444);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Mushroom Tart', 5873);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Latex Rubber Gloves Size 9', 8825);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Crab And Brie', 4389);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Turtle, Black, Dry', 1700);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Magnotta - Cab Sauv', 5982);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squeeze Bottle', 708);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Capon - Breast, Wing On', 698);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mini - Vol Au Vents', 7264);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Heavy Duty Dust Pan', 8887);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - Bran, Red', 7301);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sping Loaded Cup Dispenser', 5656);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Plastic Wrap', 155);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Shrimp - 100 / 200 Cold Water', 4725);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Doilies - 10, Paper', 8984);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sobe - Cranberry Grapefruit', 6412);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Calypso - Strawberry Lemonade', 210);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Asparagus - White, Canned', 1327);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Icecream Cone - Areo Chocolate', 622);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Turkey - Breast, Bone - In', 8997);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Rib Roast, Capless', 1401);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chilli Paste, Ginger Garlic', 7953);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coffee - Decaffeinato Coffee', 5001);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Swordfish Loin Portions', 9741);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mix - Cocktail Ice Cream', 8235);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Broom And Brush Rack Black', 7858);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Parmesan Cubes', 2549);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lettuce - Boston Bib - Organic', 9587);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cardamon Ground', 7527);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastrami', 6856);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Beef Strogonoff', 8990);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sprouts - Corn', 8930);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Red Snapper - Fillet, Skin On', 9508);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crab - Meat', 4180);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - White, Schroder And Schyl', 2375);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Kidney', 5383);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Inside Round / Top, Lean', 8439);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Chenin Blanc K.w.v.', 3175);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chutney Sauce', 928);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cabbage - Nappa', 9817);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Garbag Bags - Black', 8114);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cup - Paper 10oz 92959', 7085);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Food, Lacquer Spray', 3885);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Magnotta - Bel Paese White', 9109);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Hummus - Spread', 7649);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Barbera Alba Doc 2001', 2923);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Alicanca Vinho Verde', 7091);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tuna - Yellowfin', 423);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Red Cod Fillets - 225g', 6760);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomato - Tricolor Cherry', 2132);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Mix - Carrot', 6524);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Shortening,liqud, Fry', 763);
insert into [Shop].[dbo].[Products] (Name, Price) values ('French Pastry - Mini Chocolate', 3229);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Island Oasis - Wildberry', 9462);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Tarragon Chicken', 3259);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chicken - Wieners', 1840);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Wolf Blass, Yellow', 1812);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Batt - Ban Dream Zero', 9960);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rum - Cream, Amarula', 403);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Bagels, Mini', 5913);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin - Mix - Strawberry Rhubarb', 4204);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Octopus', 2802);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - Individual Portions', 6538);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Chocolate Chip Muffin', 1901);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Boursin, Garlic / Herbs', 2151);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake Slab', 6480);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork Casing', 1961);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Plastic Arrow Stir Stick', 9173);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Guava', 6359);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Red Bell', 1340);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Urban Zen Drinks', 1459);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes - Hot House', 1204);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ketchup - Tomato', 4726);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Tenderloin - Aa', 2574);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rabbit - Saddles', 1017);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Napkin Colour', 3465);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Melon - Honey Dew', 3848);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tabasco Sauce, 2 Oz', 5877);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bagelers - Cinn / Brown', 6894);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crawfish', 6160);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cocoa Feuilletine', 4533);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Puff Pastry - Slab', 1879);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - French Mini Assorted', 7545);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Water Chestnut - Canned', 7875);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sausage - Breakfast', 8007);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mcguinness - Blue Curacao', 8264);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Chardonnay Mondavi', 8701);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Manchego, Spanish', 9313);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Red Bell', 8872);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Container - Hngd Cll Blk 7x7x3', 8686);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Carbonated Water - Blackcherry', 2347);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Puree - Strawberry', 7199);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squid U5 - Thailand', 3948);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - La Sauvagine', 9679);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Quail - Eggs, Fresh', 1048);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Assorted Desserts', 4747);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lotus Rootlets - Canned', 2109);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mcgillicuddy Vanilla Schnap', 6322);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Pelee Island Merlot', 6800);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Bistro White', 1947);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Venison - Racks Frenched', 814);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Champagne - Brights, Dry', 1600);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Grapefruit, 341 Ml', 7725);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bagel - Everything Presliced', 7333);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Thousand Island', 8330);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Taylors Reserve', 1435);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lychee - Canned', 8871);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Red Snapper - Fresh, Whole', 7480);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells - Tomato', 1503);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Macadamia', 1329);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cocoa Butter', 8630);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Vodka Blush', 332);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Trout - Smoked', 6576);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Guinea Fowl', 5238);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Triangle White', 1634);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ice - Clear, 300 Lb For Carving', 4972);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pop - Club Soda Can', 7927);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cod - Fillets', 5242);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Vermacelli - Sprinkles, Assorted', 1977);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Baked Cinnamon Stick', 7327);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tart Shells - Sweet, 3', 1842);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Duck - Breast', 4714);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes - Cherry, Yellow', 5842);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Marzipan 50/50', 2734);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Prunes - Pitted', 4872);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lamb - Pieces, Diced', 4624);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Magnotta - Bel Paese White', 136);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Apple - Granny Smith', 6606);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beer - Camerons Cream Ale', 6419);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Gatorade - Xfactor Berry', 8659);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Escargot Puff', 2421);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cup - 6oz, Foam', 9554);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Apple, 1.36l', 3404);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Seafood Assortment', 2534);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Frangelico', 687);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Petit Baguette', 3342);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Demi Glace', 501);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Shrimp - 16 - 20 Cooked, Peeled', 5340);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nectarines', 6494);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Wax', 2817);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cups 10oz Trans', 5011);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coffee Cup 8oz 5338cd', 5418);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lidsoupcont Rp12dn', 4600);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nantucket Cranberry Juice', 1014);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pail - 4l White, With Handle', 6139);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake - Miini Cheesecake Cherry', 9310);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Goat - Leg', 901);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chicken - Whole Roasting', 4193);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Mini Hamburger Bun', 907);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup Campbells Beef With Veg', 9305);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Parasol Pick Stir Stick', 8788);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rum - Cream, Amarula', 1264);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate - Compound Coating', 1703);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sea Bass - Whole', 9311);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Egg - Salad Premix', 8747);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nacho Chips', 6517);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coconut - Creamed, Pure', 3539);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Fork - Plastic', 4334);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Beef Noodle', 8638);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Scotch - Queen Anne', 2821);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes - Yellow Hot House', 2514);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Vinegar - Raspberry', 7087);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ecolab - Hand Soap Form Antibac', 3608);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Container - Hngd Cll Blk 7x7x3', 1902);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 81x81 Colour', 9517);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Roll, Whole Wheat', 6309);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Montecillo Rioja Crianza', 6314);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup Campbells Turkey Veg.', 1541);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Ciabatta Buns', 4306);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bagel - Whole White Sesame', 8690);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lumpfish Black', 1110);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Campari', 3003);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Semi Dry Riesling Vineland', 1563);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lamb - Shoulder', 1231);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cotton Wet Mop 16 Oz', 4913);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate - Unsweetened', 1315);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cherries - Bing, Canned', 4868);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coconut - Creamed, Pure', 6624);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lotus Rootlets - Canned', 276);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells, Minestrone', 7970);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Cream Cheese', 1349);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ocean Spray - Kiwi Strawberry', 6640);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Cotes Du Rhone Parallele', 2210);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mangostein', 5132);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Romano, Grated', 8975);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sobe - Cranberry Grapefruit', 4191);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Spice - Montreal Steak Spice', 3367);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ranchero - Primerba, Paste', 1851);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Jam - Raspberry,jar', 3690);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Rib Roast, Cap On', 239);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sandwich Wrap', 9547);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chicken - Leg, Fresh', 6872);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - White, Mix', 500);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chicken - Tenderloin', 4196);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Syrup - Kahlua Chocolate', 4849);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cilantro / Coriander - Fresh', 632);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Mango Chevre', 1922);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin - Mix - Creme Brule 15l', 4280);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Goulash Seasoning', 7772);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Stoneliegh Sauvignon', 1450);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Avocado', 6293);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Vaccum Bag 10x13', 4063);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Pumpernickel', 4322);
insert into [Shop].[dbo].[Products] (Name, Price) values ('7up Diet, 355 Ml', 4639);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Fava Fresh', 3822);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Cave Springs Dry Riesling', 9555);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - Corn, Fine', 6796);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tea - Mint', 9145);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sherry - Dry', 6535);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 90x90 Colour', 6928);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Crusty Italian Poly', 9315);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Energy Drink Bawls', 302);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salt - Rock, Course', 4084);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tuna - Loin', 4131);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Neckerchief Blck', 5702);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Asparagus - Mexican', 9272);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ice Cream - Turtles Stick Bar', 8649);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Gatorade - Orange', 3683);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dooleys Toffee', 7207);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pheasants - Whole', 4674);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Italian Sesame Poly', 5297);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squeeze Bottle', 9320);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salmon Atl.whole 8 - 10 Lb', 6066);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Avocado', 7691);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Gingerale - Diet - Schweppes', 2047);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Verve - Chipotle Chicken', 6711);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Hazelnut', 217);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tart Shells - Sweet, 4', 5532);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Basil - Seedlings Cookstown', 1167);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Canadian Emmenthal', 317);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Black Bean, Dry', 1423);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Clementine', 33);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Water - Evian 355 Ml', 9946);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef Tenderloin Aaa', 4639);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tea - Darjeeling, Azzura', 5137);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Grenadine', 8245);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread Cranberry Foccacia', 9680);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Sausage Rolls', 5875);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Paper Towel Touchless', 5276);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Longos - Greek Salad', 9741);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Multigrain, Loaf', 1586);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Shrimp - 100 / 200 Cold Water', 4607);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Potatoes - Instant, Mashed', 5680);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beets - Candy Cane, Organic', 3759);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rice Wine - Aji Mirin', 1180);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flax Seed', 2854);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oysters - Smoked', 4611);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - White, Ground', 1899);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Cooking', 15);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Honey - Liquid', 3993);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Top Sirloin', 7852);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Vinegar - Balsamic', 627);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Turkey Leg With Drum And Thigh', 3102);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Malbec Trapiche Reserve', 3136);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ice Cream - Strawberry', 3524);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Red Snapper - Fresh, Whole', 6789);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Myers Planters Punch', 3282);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Bocconcini', 5182);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Prune', 7097);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ecolab - Mikroklene 4/4 L', 7571);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Rolls, Corn', 3736);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Bocconcini', 3113);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oranges - Navel, 72', 140);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cactus Pads', 6047);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Magnotta - Red, Baco', 5752);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Goat With Herbs', 3292);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bacardi Limon', 3290);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Artichoke - Hearts, Canned', 7534);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Pineapple, 48 Oz', 7934);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Quail - Jumbo Boneless', 7710);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pasta - Fusili Tri - Coloured', 3285);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Manischewitz Concord', 8283);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chinese Foods - Chicken Wing', 2411);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Turnip - White, Organic', 8338);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 53x53 White', 4935);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Kidney, Red Dry', 299);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Yellow', 5659);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pate - Cognac', 6063);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Broom And Broom Rack White', 1480);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Mozzarella, Shredded', 9348);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Green', 7489);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mints - Striped Red', 1759);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salmon Atl.whole 8 - 10 Lb', 2525);
insert into [Shop].[dbo].[Products] (Name, Price) values ('The Pop Shoppe - Grape', 9586);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lobster - Tail 6 Oz', 5618);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Steampan Lid', 4805);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sour Cream', 4874);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dill - Primerba, Paste', 5785);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bagels Poppyseed', 6946);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wild Boar - Tenderloin', 4972);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Batt - Choc Chk', 5108);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Chilli Seeds Mild', 8517);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Two Oceans Cabernet', 8138);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cornflakes', 7613);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bag Clear 10 Lb', 39);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crawfish', 6299);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Roll, Calabrese', 5263);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Celery Root', 9620);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ecolab - Balanced Fusion', 2713);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake - Mini Cheesecake', 5740);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Onions - Green', 9447);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Liver', 1610);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tart - Raisin And Pecan', 6419);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Top Butt', 2000);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pears - Anjou', 3842);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nut - Almond, Blanched, Sliced', 8493);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Trueblue - Blueberry', 9451);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rosemary - Primerba, Paste', 7900);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggplant - Asian', 3);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese Cloth No 60', 7);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crush - Grape, 355 Ml', 4993);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Cottage Cheese', 4730);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Compound - Pear', 294);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Artichokes - Knobless, White', 2310);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beer - Moosehead', 4420);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Fond - Chocolate', 5529);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Saint - Bris 2002, Sauv', 1166);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Pita', 9556);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Raisin - Golden', 938);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Straw - Regular', 4386);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Ricotta', 8841);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Kale - Red', 2083);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lamb - Leg, Bone In', 218);
insert into [Shop].[dbo].[Products] (Name, Price) values ('The Pop Shoppe - Grape', 3381);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggplant - Asian', 5504);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Potatoes - Idaho 80 Count', 5782);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Shrimp - 16 - 20 Cooked, Peeled', 4497);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Scallops - U - 10', 7549);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Carrot - Individual', 6688);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beets - Candy Cane, Organic', 573);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sour Puss - Tangerine', 9406);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Heavy Duty Dust Pan', 654);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chivas Regal - 12 Year Old', 7687);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dasheen', 6761);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Baked Cinnamon Stick', 1905);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Spring Roll, Veg', 227);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Charddonnay Errazuriz', 833);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pasta - Detalini, White, Fresh', 6989);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Mosaic Zweigelt', 6951);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Shortening - All - Purpose', 9465);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Cambozola', 9111);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pear - Packum', 8758);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squid - Breaded', 4220);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rabbit - Legs', 2317);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Gouda', 3945);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake Sheet Combo Party Pack', 8469);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - White, Mosel Gold', 2928);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Suckling Pig', 9654);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Sushi Flat Iron Steak', 6018);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepperoni Slices', 1220);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Alsace Riesling Reserve', 9052);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Asiago', 5389);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Apricots Fresh', 5193);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lemons', 1065);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mushroom - Lg - Cello', 2547);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nut - Cashews, Whole, Raw', 2059);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Wolf Blass, Yellow', 5146);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sobe - Lizard Fuel', 4491);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - White, Colubia Cresh', 7693);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes Tear Drop', 5343);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Quail - Jumbo Boneless', 2816);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Loaf Pan - 2 Lb, Foil', 8967);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sloe Gin - Mcguinness', 9168);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Whmis - Spray Bottle Trigger', 2618);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Beef Stew', 8204);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lettuce - Lolla Rosa', 3356);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rice - Long Grain', 5644);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Foam Espresso Cup Plain White', 4342);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rum - Dark, Bacardi, Black', 5678);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flax Seed', 5405);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Mix - Lemon Cranberry', 390);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Blue', 1866);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Snapple Raspberry Tea', 5356);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - Semolina', 4628);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake - Cheese Cake 9 Inch', 6744);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Everfresh Products', 6070);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Loin', 484);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Grapefruit - White', 2458);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squash - Pepper', 5995);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Food Colouring - Blue', 8671);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ecolab - Solid Fusion', 1604);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Roll, Soft White Round', 9529);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cod - Black Whole Fillet', 4724);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Icecream - Dstk Cml And Fdg', 8861);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Capers - Pickled', 2782);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pesto - Primerba, Paste', 7245);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chef Hat 20cm', 6540);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Potatoes - Pei 10 Oz', 2180);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Cabernet Sauvignon', 5698);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Venison - Striploin', 864);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lady Fingers', 9473);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chinese Foods - Thick Noodles', 7833);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ham - Cooked Italian', 2172);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Brie,danish', 338);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Neckerchief Blck', 4106);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Concha Y Toro', 2501);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Oka', 4900);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Compound - Rum', 4328);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Leg, Provimi - 50 Lb Max', 3071);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ketchup - Tomato', 2371);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Turkey - Breast, Boneless Sk On', 1731);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate - Pistoles, Lactee, Milk', 2797);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Red Currants', 9344);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Spring Roll Wrappers', 9754);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Halibut - Steaks', 85);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Pita', 4690);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squid - Breaded', 8293);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - Sweet N Low, Individual', 6190);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mayonnaise - Individual Pkg', 5241);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Jackson Triggs Okonagan', 1312);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake Circle, Foil, Scallop', 6830);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal Inside - Provimi', 5147);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ham - Smoked, Bone - In', 3534);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Hipnotiq Liquor', 538);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Carbonated Water - Peach', 6002);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oxtail - Cut', 3137);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Samosa - Veg', 9634);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lamb - Pieces, Diced', 9564);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crackers - Soda / Saltins', 6583);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - French Onion', 3706);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mushroom - White Button', 8817);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pasta - Rotini, Dry', 80);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Parsnip', 2792);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Niagara,vqa Reisling', 4558);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Goulash Seasoning', 7961);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chutney Sauce', 8603);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bacon Strip Precooked', 615);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Plastic Arrow Stir Stick', 4646);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Stoneliegh Sauvignon', 1121);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Extract - Raspberry', 258);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nantucket - 518ml', 1187);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tea - Orange Pekoe', 786);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sproutsmustard Cress', 9542);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Valpolicella Masi', 2153);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Batt - Choc Chk', 2410);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Raspberries - Frozen', 7839);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Short Ribs', 6646);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Carbonated Water - Orange', 5620);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Chardonnay South', 5649);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tart - Pecan Butter Squares', 4882);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Baking Powder', 3269);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ecolab - Ster Bac', 8239);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Calabrese Baguette', 2873);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Beaujolais Villages', 9251);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Cotes Du Rhone', 8251);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Chicken Satay', 549);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - Cubes', 1280);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Apricots Fresh', 3135);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Piper Heidsieck Brut', 8295);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Scotch Bonnet', 8880);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Blue Nun Qualitatswein', 1342);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beer - Mill St Organic', 2312);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lid - 16 Oz And 32 Oz', 1619);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lettuce - Treviso', 3070);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Butter Balls Salted', 5335);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sparkling Wine - Rose, Freixenet', 8298);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Beef Stew', 9112);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Fib N9 - Prague Powder', 1090);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Honey - Lavender', 487);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup Campbells - Tomato Bisque', 8437);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Onions - Green', 2282);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - White Packet', 5986);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Whmis - Spray Bottle Trigger', 2502);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Turkey - Breast, Smoked', 5080);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Miso - Soy Bean Paste', 5382);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pineapple - Regular', 4925);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Chardonnay South', 4599);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cookies - Englishbay Chochip', 9895);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sherbet - Raspberry', 4550);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rosemary - Dry', 3434);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Havarti, Roasted Garlic', 4895);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Garlic - Primerba, Paste', 2391);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Strawberries - California', 547);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bulgar', 4402);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cup - Paper 10oz 92959', 8489);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Extract - Vanilla,artificial', 3564);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bag - Clear 7 Lb', 8348);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Iced Tea - Lemon, 340ml', 5911);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Mix - Banana Nut', 3873);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Asparagus - White, Fresh', 655);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mustard - Seed', 5306);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nantucket Pine Orangebanana', 9964);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Arizona - Green Tea', 3433);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Alize Sunset', 1227);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes - Yellow Hot House', 7709);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bandage - Finger Cots', 1991);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - White, Unsliced', 2389);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Chateau Aqueria Tavel', 9277);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Liver', 7113);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sprouts - Baby Pea Tendrils', 8696);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beer - True North Lager', 839);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal Inside - Provimi', 1857);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cleaner - Lime Away', 1595);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Asparagus - Green, Fresh', 4736);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Jolt Cola', 2892);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Plate Pie Foil', 2802);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salt - Rock, Course', 6344);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Liver', 2477);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Ranch Dressing', 2209);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pasta - Cannelloni, Sheets, Fresh', 8199);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Blueberries - Frozen', 6926);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Sicilia Igt Nero Avola', 2613);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate Bar - Reese Pieces', 8142);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bandage - Flexible Neon', 3771);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Chili Veg', 4397);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread Sour Rolls', 2916);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Chateau Timberlay', 1011);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sausage - Andouille', 3067);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Leg', 8832);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Club Soda - Schweppes, 355 Ml', 8637);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ezy Change Mophandle', 5922);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rosemary - Primerba, Paste', 628);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Sogrape Mateus Rose', 6251);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Manischewitz Concord', 8381);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Peppercorns - Green', 2669);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Lurton Merlot De', 3568);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sole - Dover, Whole, Fresh', 5705);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bagel - Whole White Sesame', 276);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Capon - Breast, Wing On', 6254);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beer - Moosehead', 2890);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork Casing', 5324);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Molasses - Fancy', 9129);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Sauvignon Blanc', 9304);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Cheddar, Medium', 2143);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Blueberries', 9953);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tequila - Sauza Silver', 583);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Steampan - Half Size Shallow', 3221);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - Splenda Sweetener', 3247);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Alize Red Passion', 8426);
insert into [Shop].[dbo].[Products] (Name, Price) values ('The Pop Shoppe - Black Cherry', 7717);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Pain Au Liat X12', 2975);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Scallops - In Shell', 7670);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tuna - Bluefin', 5661);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sausage - Breakfast', 4475);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bar - Granola Trail Mix Fruit Nut', 7351);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Spinach - Packaged', 630);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Ej Gallo Sierra Valley', 1825);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rabbit - Whole', 793);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate - Milk, Callets', 6569);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coffee - Dark Roast', 1840);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mushroom - Enoki, Fresh', 883);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Onions - Dried, Chopped', 906);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Belly Fresh', 5905);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup Campbells - Italian Wedding', 6136);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Hazelnut', 9672);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rum - Coconut, Malibu', 3612);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Hinge Container 6', 7884);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Marble', 760);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beer - Guiness', 3437);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Smirnoff Green Apple Twist', 7554);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Loquat', 7971);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Paper Cocktail Umberlla 80 - 180', 8307);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Red Snapper - Fillet, Skin On', 1970);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tea - Jasmin Green', 5631);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Italian Sesame Poly', 7975);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Seabream Whole Farmed', 2468);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mangostein', 9304);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ham - Procutinni', 9866);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Kellogs Raisan Bran Bars', 9771);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chambord Royal', 4212);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ezy Change Mophandle', 7484);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pasta - Penne, Lisce, Dry', 9978);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Spinach - Baby', 3491);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dip - Tapenade', 317);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cafe Royale', 7023);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Quail - Jumbo Boneless', 903);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tortillas - Flour, 10', 4715);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sobe - Orange Carrot', 8541);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mousse - Banana Chocolate', 2495);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Plate Foam Laminated 9in Blk', 1388);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Gouda', 6958);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Chicken', 7440);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bok Choy - Baby', 1542);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Paper Towel Touchless', 2472);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bacardi Mojito', 9830);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lotus Leaves', 2749);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rambutan', 2720);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 54x54 Colour', 8500);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tia Maria', 1867);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Batt - Ban Dream Zero', 1845);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Orangina', 1565);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - French Can Pea', 3867);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Chicken', 3141);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Zonnebloem Pinotage', 4153);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Barley - Pearl', 9204);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Energy - Boo - Koo', 3207);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup Campbells Turkey Veg.', 5202);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Pablano', 6919);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Soya, Light', 2415);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pasta - Orzo, Dry', 5129);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Prosecco Valdobiaddene', 2116);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Gooseberry', 5075);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flavouring - Rum', 611);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Thyme - Dried', 4808);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Prune', 7648);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squid - Tubes / Tenticles 10/20', 4627);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Lamancha Do Crianza', 3468);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oats Large Flake', 4778);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Puree - Kiwi', 423);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Mini Hamburger Bun', 9451);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mushroom Morel Fresh', 4708);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salmon - Canned', 6417);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lettuce - Mini Greens, Whole', 9306);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Huck Towels White', 6229);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Container - Clear 32 Oz', 2449);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce Bbq Smokey', 3413);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crush - Grape, 355 Ml', 6005);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sobe - Tropical Energy', 7909);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pineapple - Canned, Rings', 2969);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Icecream - Dstk Strw Chseck', 8986);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Mint', 79);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Truffle - Peelings', 8588);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Fudge - Chocolate Fudge', 1369);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Truffle - Whole Black Peeled', 4072);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Anisette - Mcguiness', 4079);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ice Cream Bar - Hagen Daz', 2992);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sobe - Liz Blizz', 528);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nut - Peanut, Roasted', 6637);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggplant - Asian', 8482);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Frangelico', 2261);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - French Onion, Dry', 3375);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tortillas - Flour, 8', 9934);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Two Oceans Sauvignon', 5538);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Puree - Blackcurrant', 9317);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dasheen', 7536);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Iced Tea Concentrate', 5330);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Arctic Char - Fillets', 8683);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squid Ink', 7110);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Extract - Lemon', 4957);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bok Choy - Baby', 7910);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Carbonated Water - Peach', 604);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sobe - Lizard Fuel', 7726);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - All Purpose', 132);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lamb Tenderloin Nz Fr', 3676);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Croissants Thaw And Serve', 9761);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Mosaic Zweigelt', 474);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Energy Drink - Franks Original', 3118);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Meldea Green Tea Liquor', 3077);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crackers - Soda / Saltins', 2488);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Kellogs Special K Cereal', 873);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Julienne, Frozen', 8040);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Potatoes - Purple, Organic', 1258);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pasta - Penne, Lisce, Dry', 418);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nori Sea Weed - Gold Label', 1497);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Marjoram - Fresh', 7529);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - Splenda Sweetener', 5626);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake - French Pear Tart', 8867);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chicken - Base', 21);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - George Duboeuf Rose', 9448);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Noodles - Cellophane, Thin', 6706);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Cotes Du Rhone', 7728);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Inside Round', 8041);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pail - 15l White, With Handle', 3268);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Fava, Canned', 2244);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Truffle, White', 9544);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lid - 16 Oz And 32 Oz', 9048);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - English Muffin', 1600);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Cave Springs Dry Riesling', 8636);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Basil - Seedlings Cookstown', 3098);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Longos - Lasagna Beef', 5992);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Magnotta - Red, Baco', 891);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lettuce - Sea / Sea Asparagus', 2491);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Noodles - Steamed Chow Mein', 9139);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Heavy Duty Dust Pan', 7074);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Muscadet Sur Lie', 9806);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Steel Wool', 8931);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bar Bran Honey Nut', 2072);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Mix - Lemon Cranberry', 370);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Zucchini - Yellow', 9898);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crawfish', 7948);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork Loin Bine - In Frenched', 3002);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Yogurt - Blueberry, 175 Gr', 8490);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Key Limepoppy Seed Tea', 3337);
insert into [Shop].[dbo].[Products] (Name, Price) values ('V8 Pet', 2732);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mousse - Mango', 6580);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rice - Basmati', 4629);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Arctic Char - Fillets', 1465);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Gato Negro Cabernet', 589);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Urban Zen Drinks', 9113);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - George Duboeuf Rose', 7323);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lemonade - Mandarin, 591 Ml', 610);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Gravy, Au Jus, Mix', 7387);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Black, Whole', 787);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Shank, Pieces', 9200);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Bistro White', 1702);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Base Broth Beef', 9546);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells, Lentil', 6712);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Trueblue - Blueberry', 7072);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Apple, 500 Ml', 5128);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bonito Flakes - Toku Katsuo', 2760);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Brandy - Orange, Mc Guiness', 8443);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Milk - 2%', 9736);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Onions - Red Pearl', 7788);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tea - Orange Pekoe', 5436);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Pablano', 5923);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal Inside - Provimi', 8560);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nut - Pecan, Halves', 9863);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Jolt Cola - Red Eye', 744);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nut - Peanut, Roasted', 4394);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Water - Mineral, Carbonated', 6670);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chick Peas - Dried', 1155);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nantucket Pine Orangebanana', 4593);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Monkfish Fresh - Skin Off', 9416);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Frangelico', 894);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggplant - Baby', 4828);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dawn Professionl Pot And Pan', 7340);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Caesar Dressing', 5146);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Vineland Estate Semi - Dry', 8499);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Pinot Noir Stoneleigh', 4532);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Swiss Chard', 1400);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wheat - Soft Kernal Of Wheat', 4994);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Fine', 6486);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Barolo Fontanafredda', 6353);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Brandy Apricot', 8331);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper Squash', 1235);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nantucket - Orange Mango Cktl', 3540);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Stock - Beef, White', 72);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ginger - Ground', 3560);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Seafood Assortment', 8379);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pop Shoppe Cream Soda', 9667);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Napkin Colour', 8171);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dates', 4682);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Seafood Assortment', 3125);
insert into [Shop].[dbo].[Products] (Name, Price) values ('V8 Pet', 6102);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nestea - Iced Tea', 8148);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Ox Tongue, Pickled', 3661);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salmon Steak - Cohoe 6 Oz', 21);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tuna - Bluefin', 8365);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - Brown', 9536);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cookie Chocolate Chip With', 4552);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Plain Baked Croissant', 3157);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Trout - Rainbow, Frozen', 1656);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Kobe Striploin', 3099);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cocoa Feuilletine', 5448);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Melon - Honey Dew', 111);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ice Cream - Super Sandwich', 9205);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Mozzarella, Shredded', 6164);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Gloves - Goldtouch Disposable', 8987);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Truffle Shells - White Chocolate', 1864);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Peach - Halves', 1070);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pomegranates', 3757);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Puligny Montrachet A.', 5521);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lobster - Tail, 3 - 4 Oz', 3502);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Steamers White', 2883);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Multigrain, Loaf', 1433);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Apples - Sliced / Wedge', 543);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef Flat Iron Steak', 3452);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flower - Daisies', 4963);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup Campbells Beef With Veg', 2825);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Syrup - Monin - Granny Smith', 4202);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Jafflin Bourgongone', 7853);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bagelers - Cinn / Brown', 575);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mushroom - Portebello', 9784);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tea - Herbal Orange Spice', 1057);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rabbit - Legs', 2243);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Island Oasis - Lemonade', 1117);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Hinge - 211n', 9498);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Salted', 8582);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Hog / Sausage Casing - Pork', 2400);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Orange, 341 Ml', 2160);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Kolrabi', 2812);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Foam Dinner Plate', 9432);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Liqueur Banana, Ramazzotti', 3959);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Baron De Rothschild', 7498);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lid - 16 Oz And 32 Oz', 8392);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flavouring Vanilla Artificial', 2928);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Havarti, Roasted Garlic', 512);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Truffle Cups Green', 200);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Monkfish - Fresh', 6004);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Puree - Guava', 5381);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Coconut', 3344);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Bones', 1258);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Lobster Phyllo Roll', 7117);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rabbit - Whole', 813);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Tio Pepe Sherry Fino', 7494);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine La Vielle Ferme Cote Du', 4461);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Olives - Black, Pitted', 3311);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chicken - Leg, Boneless', 5699);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Muffin Puck Ww Carrot', 7756);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - Chickpea', 4515);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Baked Cinnamon Stick', 2633);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggwhite Frozen', 2666);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Appetizer - Mushroom Tart', 7272);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggplant Italian', 9772);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Prune', 1953);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - White, French Cross', 2349);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Placido Pinot Grigo', 7691);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Sushi Flat Iron Steak', 5449);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 62x114 White', 9086);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Thyme - Fresh', 9838);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Parsley Italian - Fresh', 8906);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Plums - Red', 1157);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Canadian Pea, Dry Mix', 9529);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Carrots - Purple, Organic', 4359);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Red, Gamay Noir', 2523);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dried Figs', 806);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mahi Mahi', 758);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Shred Cheddar / Mozza', 8777);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Cottage Cheese', 3758);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Container - Hngd Cll Blk 7x7x3', 2773);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Scotch - Queen Anne', 6709);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Ham Hocks - Smoked', 4121);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wiberg Super Cure', 8850);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tart Shells - Savory, 4', 9427);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Madeira', 5132);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Orange Roughy 6/8 Oz', 7446);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Jolt Cola', 2703);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sparkling Wine - Rose, Freixenet', 5581);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cranberries - Fresh', 931);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Gato Negro Cabernet', 162);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Marble', 8171);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate - Pistoles, Lactee, Milk', 2140);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Jolt Cola', 8715);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Vidal Icewine Magnotta', 5647);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Chateauneuf Du Pape', 7063);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coffee - Almond Amaretto', 8118);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coffee Cup 8oz 5338cd', 8873);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Chili Powder', 1062);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce - Plum', 2822);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 120 Round White', 355);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Loaf Pan - 2 Lb, Foil', 6727);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Fish - Bones', 9513);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Bresaola', 2668);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sauce Tomato Pouch', 6189);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lettuce - Boston Bib - Organic', 7963);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flower - Carnations', 2018);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Bresaola', 5270);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tuna - Loin', 3577);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mince Meat - Filling', 1621);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Oil - Cooking Spray', 7175);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Asiago', 2914);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cream Of Tartar', 9917);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lettuce - Red Leaf', 5268);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - Semolina', 7523);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Plate - Foam, Bread And Butter', 6366);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Baked Cinnamon Stick', 5641);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Squid Ink', 8865);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Turkey - Breast, Double', 3322);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes - Grape', 9466);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Napkin White - Starched', 3922);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eel Fresh', 5286);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Flour - Chickpea', 1765);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Dried Figs', 5623);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Garlic - Peeled', 985);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Fat Bastard Merlot', 2392);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pail For Lid 1537', 2081);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Chili Veg', 1732);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cherries - Maraschino,jar', 4370);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Jolt Cola - Red Eye', 8029);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bread - Crusty Italian Poly', 1057);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Shichimi Togarashi Peppeers', 1437);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cape Capensis - Fillet', 7637);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coconut - Creamed, Pure', 4340);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Guinea Fowl', 8394);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crab - Claws, Snow 16 - 24', 143);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomato - Peeled Italian Canned', 1483);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tea - English Breakfast', 9056);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pastry - Mini French Pastries', 4856);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nut - Pecan, Pieces', 1490);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Nantucket Cranberry Juice', 6757);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Coffee - Irish Cream', 6875);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crackers - Melba Toast', 6325);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Ginger - Crystalized', 139);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cabbage - Savoy', 5481);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pear - Halves', 1866);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pepper - Gypsy Pepper', 3414);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tart - Raisin And Pecan', 885);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cheese - Brie Roitelet', 3143);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Miso - Soy Bean Paste', 5600);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Strawberries - California', 967);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tamarillo', 6538);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Taro Leaves', 8126);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salmon - Atlantic, Fresh, Whole', 5557);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bag - Bread, White, Plain', 4515);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pate - Liver', 5978);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Chicken And Wild Rice', 2570);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sugar - Invert', 7537);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pork - Ham, Virginia', 3028);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Touraine Azay - Le - Rideau', 2322);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Veal - Provimi Inside', 5622);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Steam Pan Full Lid', 8425);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Smirnoff Green Apple Twist', 30);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cumin - Whole', 6211);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beans - Turtle, Black, Dry', 1955);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Asparagus - Mexican', 3292);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggs - Extra Large', 62);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Doilies - 5, Paper', 7482);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sansho Powder', 2868);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rice - 7 Grain Blend', 6291);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Barolo Fontanafredda', 3066);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sage - Ground', 4467);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cocoa Powder - Dutched', 1409);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Parasol Pick Stir Stick', 5069);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate Bar - Reese Pieces', 1225);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Smirnoff Green Apple Twist', 8230);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Potatoes - Pei 10 Oz', 2873);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bacardi Breezer - Tropical', 8310);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sage - Fresh', 9624);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Spinach - Baby', 4609);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salt - Seasoned', 5146);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Clamato, 341 Ml', 7419);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cocoa Powder - Natural', 9431);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rabbit - Saddles', 3947);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Table Cloth 62x114 Colour', 2996);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake - Cake Sheet Macaroon', 7108);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Zinfandel Rosenblum', 846);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lobak', 8722);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lamb Leg - Bone - In Nz', 9028);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Barolo Fontanafredda', 3147);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chutney Sauce', 2145);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Daves Island Stinger', 5904);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Baking Powder', 4811);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Mas Chicet Rose, Vintage', 5339);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cherries - Fresh', 9623);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Campbells Chili Veg', 6479);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Pumpkin', 1811);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tomatoes - Orange', 6207);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Pinot Grigio Collavini', 9442);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - Masi Valpolocell', 3125);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Stock - Veal, Brown', 7688);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Wine - White, Rivesling, Henry Of', 7870);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Cake Sheet Combo Party Pack', 6229);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Bagelers - Cinn / Brown', 5149);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef Tenderloin Aaa', 9759);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Sprouts - Alfalfa', 7030);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lychee', 3161);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chocolate - Dark', 8972);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Mudslide', 1244);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Russian Prince', 5751);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Soup - Base Broth Beef', 9020);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tuna - Canned, Flaked, Light', 8992);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Tuna - Fresh', 3636);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Orange - Canned, Mandarin', 3282);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice - Happy Planet', 58);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Island Oasis - Cappucino Mix', 476);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Salt - Kosher', 1094);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lidsoupcont Rp12dn', 766);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Crab - Claws, Snow 16 - 24', 2238);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Carbonated Water - Raspberry', 5846);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beer - Steamwhistle', 9307);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Juice Peach Nectar', 8943);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Chips - Assorted', 7696);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Lambcasing', 6831);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Eggplant - Asian', 8753);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Orange - Blood', 477);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Beef - Kobe Striploin', 9036);
insert into [Shop].[dbo].[Products] (Name, Price) values ('Rabbit - Saddles', 3601);